# fifth version
name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t awshotelfrontend .
          docker tag awshotelfrontend:latest softa67/awshotelfrontend:latest

      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push softa67/awshotelfrontend:latest

      - name: EC2 SSH > Pull and Start Docker Container for Frontend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull softa67/awshotelfrontend:latest
            docker stop $(docker ps -a -q)
            docker run --rm -d -p 80:3000 softa67/awshotelfrontend:latest
            docker run --rm -d -p 3000:3000 softa67/awshotelbackend:latest
